# =============================================================================
# SYSTEM MONITOR - Host Health Monitoring
# =============================================================================
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

# =============================================================================
# STATISTICS SENSORS
# =============================================================================
# 24h energy consumption statistics using the statistics platform

- platform: statistics
  entity_id: sensor.ftx_energy
  name: "FTX Energi 24h"
  state_characteristic: change
  max_age:
    hours: 24

- platform: statistics
  entity_id: sensor.casa_energy
  name: "CASA Energi 24h"
  state_characteristic: change
  max_age:
    hours: 24

- platform: statistics
  entity_id: sensor.frys_energy
  name: "Frys Energi 24h"
  state_characteristic: change
  max_age:
    hours: 24

- platform: statistics
  entity_id: sensor.ida_smartplug_energy
  name: "Ida Energi 24h"
  state_characteristic: change
  max_age:
    hours: 24

- platform: statistics
  entity_id: sensor.torktumlare_energi
  name: "Torktumlare Energi 24h"
  state_characteristic: change
  max_age:
    hours: 24

- platform: statistics
  entity_id: sensor.smart_meter_ts_65a_3_verklig_energi_forbrukad
  name: "Total Energi 24h Wh"
  state_characteristic: change
  max_age:
    hours: 24

# =============================================================================
# HISTORY STATS - Daily Runtime Tracking
# =============================================================================
- platform: history_stats
  name: "FTX Drifttid 24h"
  entity_id: binary_sensor.ftx_aktiv
  state: "on"
  type: time
  start: "{{ now() - timedelta(hours=24) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: "CASA Drifttid 24h"
  entity_id: binary_sensor.casa_aktiv
  state: "on"
  type: time
  start: "{{ now() - timedelta(hours=24) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: "Frys Kompressor Drifttid 24h"
  entity_id: binary_sensor.frys_kompressor
  state: "on"
  type: time
  start: "{{ now() - timedelta(hours=24) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: "Ida Smartplug Drifttid 24h"
  entity_id: binary_sensor.ida_smartplug_aktiv
  state: "on"
  type: time
  start: "{{ now() - timedelta(hours=24) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: "Moa Smartplug Drifttid 24h"
  entity_id: switch.moa_smartplug
  state: "on"
  type: time
  start: "{{ now() - timedelta(hours=24) }}"
  end: "{{ now() }}"
