esphome:
  name: bt-proxy-garage
  friendly_name: Bluetooth Proxy Garage

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 5min

logger:
  level: INFO

ota:
  platform: esphome
  password: !secret ota_password

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: uptime
    name: "Uptime"
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Status"
